import Head from "next/head";

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex h-screen w-screen items-center justify-center">
      <h1 className="underline">Hello from NextJS</h1>
    </main>
  </>
);
export default Home;
